### ISSUE TITLE
npx support?

### ISSUE THREAD

**Issue by hertzg** [aimnadze/fwait#1]
What do you think about adding support for `npx`? This would give ability to run this without installation using `npm` (specifically `npx` which comes with it).

This would allow:
`npx fwait ...` commands which would pull it from an npm repository and run the js file defined in the `package.json`

What are your thoughts? I could whip up a PR implementing it 🎩

**Comment by aimnadze** [comment]
Thanks for the interest.

I'm the only developer of this project and I don't think I can continuously support npm packaging by myself. If you like the project you may fork it. If somehow the AGPL license is not suitable for you I may consider changing it to another free software license of your choice. Finally, I'll happily link to that forked project from the README.

**Comment by hertzg** [comment]
I can make a pipeline automatically publishing a new version on each push to specific branch (or master) do you think it would help reduce the maintenance cost?

**Comment by aimnadze** [comment]
The problem is not the maintenance cost. `npm` is a property of Microsoft. Adding a file to my project that supports `npm` is adding a building block to Microsoft which I'd rather not to.

The software is free. Why don't you fork? I don't even as for credit for that.

**Comment by hertzg** [comment]
No worries, I just wanted to understand what was the reason behind it. I'm not sure if forking would be the best approach here but I understand your stance 👍 

Thanks!
